import { useCallback, useDeferredValue, useEffect, useMemo, useState } from 'react';
import { ArrowUpRight, Check, ChevronDown, Database, Filter, Plus, RefreshCw, Save, Search, SlidersHorizontal, Sparkles, Trash2, TriangleAlert } from 'lucide-react';
import { apiRefreshSavedScreener, apiRemoveSavedScreener, apiSaveScreener, apiSavedScreeners, apiScreenStocks, ApiError, type SavedScreener, type StockScreenerResult } from '../lib/api';
import type { StockItem } from '../types';

const presets = ['A股中市盈率小于20且市净率小于2的股票', '净利润同比增长大于30%的A股', 'ROE大于15%且资产负债率较低的A股', '银行板块中股息率较高的股票', '半导体行业中近20日涨幅靠前的股票'];
const codeLabels = /^(代码|证券代码|股票代码)$/;
const nameLabels = /^(名称|简称|证券简称|股票简称)$/;
const numberFormatter = new Intl.NumberFormat('zh-CN', { maximumFractionDigits: 2 });

function label(value: string) { return value.replace(/\(.+?\)/g, '').trim(); }
function display(value: unknown) { return value === null || value === undefined || value === '' ? '--' : typeof value === 'number' ? numberFormatter.format(value) : String(value); }
function toNumber(value: unknown): number | null { const text = String(value ?? '').replace(/,/g, '').replace(/[^\d.-]/g, ''); return text && Number.isFinite(Number(text)) ? Number(text) : null; }
function findColumn(result: StockScreenerResult, pattern: RegExp) { return result.columns.find((column) => pattern.test(label(column.label))); }
function formatTime(value: string | null) { if (!value) return '尚未更新'; const date = new Date(value); return Number.isNaN(date.valueOf()) ? value : new Intl.DateTimeFormat('zh-CN', { month: 'numeric', day: 'numeric', hour: '2-digit', minute: '2-digit' }).format(date); }

function toStock(result: StockScreenerResult, row: Record<string, unknown>): StockItem | null {
  const code = String(row[findColumn(result, codeLabels)?.key || ''] || '').replace(/\D/g, '').slice(-6);
  if (!/^\d{6}$/.test(code)) return null;
  const name = String(row[findColumn(result, nameLabels)?.key || ''] || code);
  const price = toNumber(row[result.columns.find((column) => /最新价|收盘价/.test(column.label))?.key || '']) || 0;
  const changePercent = toNumber(row[result.columns.find((column) => /涨跌幅/.test(column.label))?.key || '']) || 0;
  return { code, name, price, changePercent, volume: '--', turnover: '--', history: [] };
}

function tableColumns(result: StockScreenerResult) {
  const priority = [codeLabels, nameLabels, /最新价|收盘价/, /涨跌幅/, /市盈率\(TTM\)|市盈率/, /市净率/, /ROE/, /净利润同比|营收同比/];
  const picked: typeof result.columns = [];
  priority.forEach((pattern) => { const column = result.columns.find((item) => pattern.test(label(item.label)) && !picked.some((selected) => selected.key === item.key)); if (column) picked.push(column); });
  return picked.length ? picked : result.columns.slice(0, 8);
}

function DataQuality({ result, rows, columns }: { result: StockScreenerResult; rows: Record<string, unknown>[]; columns: StockScreenerResult['columns'] }) {
  const asOf = [...new Set(columns.map((column) => column.dateMsg).filter(Boolean))].join('、') || '接口返回时点';
  const gaps = rows.reduce((total, row) => total + columns.filter((column) => row[column.key] === null || row[column.key] === undefined || row[column.key] === '').length, 0);
  return <aside className="border-t border-slate-100 p-4 md:border-l md:border-t-0"><p className="text-xs font-semibold text-slate-700">数据口径与质量</p><dl className="mt-2 space-y-1.5 text-xs leading-5 text-slate-500"><div className="flex justify-between gap-3"><dt>数据时点</dt><dd className="text-right text-slate-700">{asOf}</dd></div><div className="flex justify-between gap-3"><dt>来源</dt><dd className="text-right text-slate-700">东方财富妙想</dd></div><div className="flex justify-between gap-3"><dt>展示覆盖</dt><dd className="text-right text-slate-700">前 {rows.length} / {result.total.toLocaleString('zh-CN')} 只</dd></div><div className="flex justify-between gap-3"><dt>字段缺口</dt><dd className={gaps ? 'text-amber-700' : 'text-emerald-700'}>{gaps ? `${gaps} 个空值` : '当前展示字段完整'}</dd></div></dl><p className="mt-2 text-[11px] leading-5 text-slate-400">候选池反映条件命中，不等于投资结论；请进入个股分析继续核验。</p></aside>;
}

interface Props { onOpenResearch: (stock: StockItem) => void; onFollowStock: (stock: StockItem) => void; followedStocks: StockItem[]; }

export function StockScreenerTab({ onOpenResearch, onFollowStock, followedStocks }: Props) {
  const [query, setQuery] = useState(presets[0]);
  const [result, setResult] = useState<StockScreenerResult | null>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [conditions, setConditions] = useState<string[]>([]);
  const [newCondition, setNewCondition] = useState('');
  const [keyword, setKeyword] = useState('');
  const [numericColumn, setNumericColumn] = useState('');
  const [numericMode, setNumericMode] = useState<'gte' | 'lte'>('gte');
  const [numericValue, setNumericValue] = useState('');
  const [sortKey, setSortKey] = useState<string | null>(null);
  const [sortDirection, setSortDirection] = useState<'asc' | 'desc'>('desc');
  const [saved, setSaved] = useState<SavedScreener[]>([]);
  const [saveName, setSaveName] = useState('');
  const [saving, setSaving] = useState(false);
  const [savedBusy, setSavedBusy] = useState<string | null>(null);
  const deferredResult = useDeferredValue(result);
  const loadSaved = useCallback(async () => { try { setSaved(await apiSavedScreeners()); } catch { /* 认证失败不阻塞临时筛选 */ } }, []);
  useEffect(() => { void loadSaved(); }, [loadSaved]);
  const columns = useMemo(() => deferredResult ? tableColumns(deferredResult) : [], [deferredResult]);
  const numericColumns = useMemo(() => deferredResult?.columns.filter((column) => deferredResult.rows.some((row) => toNumber(row[column.key]) !== null)).slice(0, 20) || [], [deferredResult]);
  const filteredRows = useMemo(() => {
    if (!deferredResult) return [];
    const text = keyword.trim().toLowerCase(); const threshold = toNumber(numericValue);
    return deferredResult.rows.filter((row) => {
      if (text && !Object.values(row).some((value) => String(value ?? '').toLowerCase().includes(text))) return false;
      if (!numericColumn || threshold === null) return true;
      const value = toNumber(row[numericColumn]); return value !== null && (numericMode === 'gte' ? value >= threshold : value <= threshold);
    });
  }, [deferredResult, keyword, numericColumn, numericMode, numericValue]);
  const rows = useMemo(() => {
    if (!sortKey) return filteredRows;
    return [...filteredRows].sort((left, right) => { const a = toNumber(left[sortKey]); const b = toNumber(right[sortKey]); const comparison = a !== null && b !== null ? a - b : String(left[sortKey] ?? '').localeCompare(String(right[sortKey] ?? ''), 'zh-CN'); return sortDirection === 'asc' ? comparison : -comparison; });
  }, [filteredRows, sortKey, sortDirection]);

  const run = async (refresh = false, queryValue = query) => {
    const value = queryValue.trim(); if (!value || loading) return;
    setLoading(true); setError(null);
    try { const next = await apiScreenStocks(value, refresh); setResult(next); setConditions(next.conditions.map((item) => item.description)); setSaveName(next.query.slice(0, 18)); setSortKey(null); }
    catch (caught) { setError(caught instanceof ApiError ? caught.message : '条件选股暂不可用，请稍后重试。'); }
    finally { setLoading(false); }
  };
  const applyConditions = () => { const value = conditions.join('，'); if (value) { setQuery(value); void run(false, value); } };
  const toggleSort = (key: string) => { if (sortKey === key) setSortDirection((value) => value === 'asc' ? 'desc' : 'asc'); else { setSortKey(key); setSortDirection('desc'); } };
  const saveCurrent = async () => { if (!result || saving) return; setSaving(true); try { const item = await apiSaveScreener(saveName, query); setSaved((items) => [item, ...items]); } catch (caught) { setError(caught instanceof ApiError ? caught.message : '保存条件失败，请稍后重试。'); } finally { setSaving(false); } };
  const refreshSaved = async (id: string) => { setSavedBusy(id); try { const item = await apiRefreshSavedScreener(id); setSaved((items) => items.map((value) => value.id === id ? item : value)); } catch (caught) { setError(caught instanceof ApiError ? caught.message : '保存条件刷新失败。'); } finally { setSavedBusy(null); } };
  const removeSaved = async (id: string) => { setSavedBusy(id); try { await apiRemoveSavedScreener(id); setSaved((items) => items.filter((item) => item.id !== id)); } catch (caught) { setError(caught instanceof ApiError ? caught.message : '删除保存条件失败。'); } finally { setSavedBusy(null); } };

  return <div className="mx-auto max-w-7xl space-y-5 pb-8">
    <section className="grid gap-5 xl:grid-cols-[minmax(0,1fr)_290px]">
      <div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex flex-wrap items-start justify-between gap-4"><div className="max-w-2xl"><div className="flex items-center gap-2 text-indigo-700"><span className="grid h-8 w-8 place-items-center rounded-lg bg-indigo-50"><SlidersHorizontal className="h-4 w-4" /></span><p className="text-sm font-bold">条件选股</p></div><h1 className="mt-3 text-xl font-bold tracking-tight text-slate-950">先形成候选池，再进入个股研究</h1><p className="mt-2 text-sm leading-6 text-slate-600">用自然语言描述你关心的行情、估值、财务或行业条件。这里输出的是研究候选，不构成买卖建议。</p></div><div className="rounded-xl bg-slate-50 px-3 py-2 text-xs leading-5 text-slate-500"><span className="font-semibold text-slate-700">数据源：</span>东方财富妙想<br />仅在提交或手动刷新时请求</div></div><form className="mt-5" onSubmit={(event) => { event.preventDefault(); void run(); }}><label htmlFor="screener-query" className="sr-only">用自然语言输入选股条件</label><div className="flex flex-col gap-2 sm:flex-row"><div className="relative min-w-0 flex-1"><Search className="pointer-events-none absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-slate-400" /><input id="screener-query" value={query} maxLength={180} onChange={(event) => setQuery(event.target.value)} placeholder="例如：ROE 大于 15%，净利润持续增长的 A 股" className="h-12 w-full rounded-xl border border-slate-300 bg-white pl-10 pr-3 text-sm text-slate-900 outline-none transition placeholder:text-slate-400 focus:border-indigo-500 focus:ring-2 focus:ring-indigo-100" /></div><button type="submit" disabled={loading || !query.trim()} className="inline-flex h-12 items-center justify-center gap-2 rounded-xl bg-indigo-600 px-5 text-sm font-semibold text-white transition hover:bg-indigo-700 disabled:cursor-wait disabled:opacity-60">{loading ? <RefreshCw className="h-4 w-4 animate-spin" /> : <Sparkles className="h-4 w-4" />}{loading ? '正在筛选…' : '生成候选池'}</button></div></form><div className="mt-3 flex flex-wrap gap-2">{presets.map((preset) => <button key={preset} type="button" onClick={() => setQuery(preset)} className={`rounded-full border px-3 py-1.5 text-xs transition ${query === preset ? 'border-indigo-200 bg-indigo-50 text-indigo-700' : 'border-slate-200 bg-white text-slate-600 hover:border-slate-300 hover:text-slate-900'}`}>{preset}</button>)}</div></div>
      <aside className="space-y-4"><div className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><div className="flex items-center justify-between"><div><h2 className="text-sm font-bold text-slate-900">已保存条件</h2><p className="mt-1 text-xs text-slate-500">每日 09:30 更新候选变化</p></div><span className="text-xs text-slate-400">{saved.length}/12</span></div>{saved.length ? <ul className="mt-3 divide-y divide-slate-100">{saved.slice(0, 5).map((item) => <li key={item.id} className="py-2.5"><div className="flex gap-2"><button type="button" onClick={() => { setQuery(item.query); if (item.lastResult) { setResult(item.lastResult); setConditions(item.lastResult.conditions.map((condition) => condition.description)); } else void run(false, item.query); }} className="min-w-0 flex-1 text-left"><span className="block truncate text-xs font-semibold text-slate-800">{item.name}</span><span className="mt-0.5 block text-[11px] text-slate-500">{item.lastDiff?.initial ? '首次记录' : item.lastDiff ? `新增 ${item.lastDiff.added?.length || 0} · 移出 ${item.lastDiff.removed?.length || 0}` : formatTime(item.lastRunAt)}</span></button><button type="button" disabled={savedBusy === item.id} onClick={() => void refreshSaved(item.id)} className="grid h-7 w-7 place-items-center rounded-md text-slate-400 hover:bg-indigo-50 hover:text-indigo-700" aria-label={`刷新 ${item.name}`}><RefreshCw className={`h-3.5 w-3.5 ${savedBusy === item.id ? 'animate-spin' : ''}`} /></button><button type="button" disabled={savedBusy === item.id} onClick={() => void removeSaved(item.id)} className="grid h-7 w-7 rounded-md text-slate-400 hover:bg-rose-50 hover:text-rose-600" aria-label={`删除 ${item.name}`}><Trash2 className="h-3.5 w-3.5" /></button></div></li>)}</ul> : <p className="mt-3 text-xs leading-5 text-slate-500">完成一次筛选后，可把常用条件保存到这里。</p>}</div></aside>
    </section>
    {error && <div role="alert" className="flex items-start gap-2 rounded-xl border border-rose-200 bg-rose-50 p-4 text-sm text-rose-800"><TriangleAlert className="mt-0.5 h-4 w-4 shrink-0" /><div><p className="font-semibold">暂时无法完成操作</p><p className="mt-1 text-rose-700">{error}</p></div></div>}
    {loading && <section className="overflow-hidden rounded-2xl border border-slate-200 bg-white"><div className="h-16 animate-pulse border-b border-slate-100 bg-slate-50" />{Array.from({ length: 8 }).map((_, index) => <div key={index} className="flex gap-4 border-b border-slate-100 px-5 py-4"><span className="h-4 w-20 animate-pulse rounded bg-slate-100" /><span className="h-4 w-28 animate-pulse rounded bg-slate-100" /><span className="h-4 flex-1 animate-pulse rounded bg-slate-100" /></div>)}</section>}
    {!loading && result && <section className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><header className="flex flex-wrap items-center justify-between gap-3 border-b border-slate-100 px-5 py-4"><div><div className="flex items-center gap-2"><h2 className="text-base font-bold text-slate-900">{result.title}</h2><span className="rounded-full bg-emerald-50 px-2 py-0.5 text-xs font-semibold text-emerald-700">{result.total.toLocaleString('zh-CN')} 只</span></div><p className="mt-1 text-xs text-slate-500">“{result.query}” · {result.sourceMeta.freshness === 'cache' ? '缓存结果' : '实时结果'} · {formatTime(result.sourceMeta.fetchedAt)}</p></div><div className="flex items-center gap-2"><button type="button" onClick={() => void run(true)} className="inline-flex h-9 items-center gap-2 rounded-lg border border-slate-200 px-3 text-xs font-semibold text-slate-700 hover:border-indigo-200 hover:text-indigo-700"><RefreshCw className="h-3.5 w-3.5" />刷新筛选</button><button type="button" onClick={() => void saveCurrent()} disabled={saving || saved.length >= 12} className="inline-flex h-9 items-center gap-2 rounded-lg bg-indigo-600 px-3 text-xs font-semibold text-white hover:bg-indigo-700 disabled:opacity-60"><Save className="h-3.5 w-3.5" />{saving ? '保存中' : '保存条件'}</button></div></header>
      <div className="grid bg-slate-50/70 md:grid-cols-[minmax(0,1fr)_300px]"><div className="p-4"><div className="flex flex-wrap items-center justify-between gap-2"><p className="text-xs font-semibold text-slate-700">可编辑条件</p><button type="button" onClick={applyConditions} disabled={!conditions.length || loading} className="text-xs font-semibold text-indigo-700 hover:text-indigo-900">应用并重新筛选</button></div><div className="mt-2 flex flex-wrap gap-2">{conditions.map((condition, index) => <span key={`${condition}-${index}`} className="inline-flex items-center gap-1 rounded-lg border border-indigo-100 bg-white px-2.5 py-1.5 text-xs text-indigo-800"><Check className="h-3 w-3 text-indigo-600" />{condition}<button type="button" onClick={() => setConditions((items) => items.filter((_, itemIndex) => itemIndex !== index))} aria-label={`移除条件 ${condition}`} className="ml-1 rounded text-indigo-400 hover:text-rose-600">×</button></span>)}</div><div className="mt-3 flex gap-2"><input value={newCondition} onChange={(event) => setNewCondition(event.target.value)} maxLength={60} placeholder="补充条件，例如：ROE 大于 15%" className="h-9 min-w-0 flex-1 rounded-lg border border-slate-200 bg-white px-3 text-xs outline-none focus:border-indigo-500" /><button type="button" onClick={() => { const value = newCondition.trim(); if (value && !conditions.includes(value)) setConditions((items) => [...items, value]); setNewCondition(''); }} className="inline-flex h-9 items-center gap-1 rounded-lg border border-slate-200 px-3 text-xs font-semibold text-slate-700 hover:border-indigo-200 hover:text-indigo-700"><Plus className="h-3.5 w-3.5" />添加</button></div><div className="mt-3 flex items-center gap-2"><input value={saveName} onChange={(event) => setSaveName(event.target.value)} maxLength={30} aria-label="保存条件名称" placeholder="保存条件名称" className="h-8 w-44 rounded-lg border border-slate-200 bg-white px-2 text-xs outline-none focus:border-indigo-500" /><span className="text-[11px] text-slate-400">保存后每日自动更新</span></div></div><DataQuality result={result} rows={filteredRows} columns={columns} /></div>
      <div className="flex flex-wrap gap-2 border-y border-slate-100 bg-white px-4 py-3"><div className="relative min-w-[180px] flex-1"><Search className="pointer-events-none absolute left-2.5 top-1/2 h-3.5 w-3.5 -translate-y-1/2 text-slate-400" /><input value={keyword} onChange={(event) => setKeyword(event.target.value)} placeholder="结果内搜索名称或代码" className="h-9 w-full rounded-lg border border-slate-200 pl-8 pr-2 text-xs outline-none focus:border-indigo-500" /></div><select value={numericColumn} onChange={(event) => setNumericColumn(event.target.value)} className="h-9 rounded-lg border border-slate-200 bg-white px-2 text-xs text-slate-700"><option value="">选择二次筛选字段</option>{numericColumns.map((column) => <option key={column.key} value={column.key}>{column.label}</option>)}</select><select value={numericMode} onChange={(event) => setNumericMode(event.target.value as 'gte' | 'lte')} disabled={!numericColumn} className="h-9 rounded-lg border border-slate-200 bg-white px-2 text-xs text-slate-700 disabled:bg-slate-50"><option value="gte">大于等于</option><option value="lte">小于等于</option></select><input value={numericValue} onChange={(event) => setNumericValue(event.target.value)} disabled={!numericColumn} inputMode="decimal" placeholder="数值" className="h-9 w-20 rounded-lg border border-slate-200 px-2 text-xs outline-none focus:border-indigo-500 disabled:bg-slate-50" /><span className="inline-flex h-9 items-center rounded-lg bg-slate-50 px-2.5 text-xs text-slate-500">当前 {rows.length} 只</span></div>
      {rows.length ? <div className="overflow-x-auto"><table className="min-w-full text-left text-sm"><thead className="bg-white text-xs text-slate-500"><tr><th className="w-10 px-3 py-3 font-medium">#</th>{columns.map((column) => <th key={column.key} className="whitespace-nowrap px-3 py-3 font-medium"><button type="button" onClick={() => toggleSort(column.key)} className="inline-flex items-center gap-1 hover:text-indigo-700">{column.label}<ChevronDown className={`h-3 w-3 transition ${sortKey === column.key && sortDirection === 'asc' ? 'rotate-180' : ''}`} /></button></th>)}<th className="sticky right-0 bg-white px-4 py-3 text-right font-medium">操作</th></tr></thead><tbody className="divide-y divide-slate-100">{rows.map((row, index) => { const stock = toStock(result, row); const key = stock?.code || `${index}-${String(row[columns[0]?.key] || '')}`; const isFollowed = Boolean(stock && followedStocks.some((item) => item.code === stock.code)); return <tr key={key} className="transition hover:bg-slate-50/80"><td className="px-3 py-3 text-xs text-slate-400">{index + 1}</td>{columns.map((column) => <td key={column.key} className={`whitespace-nowrap px-3 py-3 ${/涨跌幅/.test(column.label) && String(row[column.key]).startsWith('-') ? 'text-emerald-600' : /涨跌幅/.test(column.label) ? 'text-rose-600' : 'text-slate-700'}`}>{display(row[column.key])}</td>)}<td className="sticky right-0 bg-white px-3 py-2 text-right"><div className="flex items-center justify-end gap-1">{stock ? <><button type="button" onClick={() => onFollowStock(stock)} disabled={isFollowed} className="inline-flex h-8 items-center gap-1 rounded-lg px-2 text-xs font-medium text-slate-600 hover:bg-amber-50 hover:text-amber-700 disabled:cursor-default disabled:bg-emerald-50 disabled:text-emerald-700">{isFollowed ? '已在自选' : '加入自选'}</button><button type="button" onClick={() => onOpenResearch(stock)} className="inline-flex h-8 items-center gap-1 rounded-lg bg-indigo-600 px-2.5 text-xs font-semibold text-white hover:bg-indigo-700">分析<ArrowUpRight className="h-3.5 w-3.5" /></button></> : <span className="text-xs text-slate-400">代码不可用</span>}</div></td></tr>; })}</tbody></table></div> : <div className="p-10 text-center"><Database className="mx-auto h-8 w-8 text-slate-300" /><p className="mt-3 text-sm font-semibold text-slate-700">没有符合二次筛选的股票</p><p className="mt-1 text-xs text-slate-500">请放宽数值条件或清空结果内搜索。</p></div>}</section>}
    {!loading && !result && !error && <section className="rounded-2xl border border-dashed border-slate-300 bg-white px-6 py-12 text-center"><Filter className="mx-auto h-9 w-9 text-indigo-300" /><h2 className="mt-4 text-base font-bold text-slate-800">描述你的候选条件</h2><p className="mx-auto mt-2 max-w-lg text-sm leading-6 text-slate-500">可从估值、财务、行情、行业或指数成分股开始。系统会把自然语言拆成可检查的筛选条件。</p></section>}
  </div>;
}
