import { StrictMode, useCallback, useEffect, useRef, useState } from 'react';
import * as THREE from 'three';
import { createRoot } from 'react-dom/client';
import { Mic, MicOff, Pause, Play, Upload } from 'lucide-react';
import './letter-universe-v1.css';

const COUNT = 9000;

function makeAlphabetAtlas() {
  const canvas = document.createElement('canvas'); canvas.width = 1024; canvas.height = 1024;
  const ctx = canvas.getContext('2d')!; ctx.clearRect(0, 0, 1024, 1024); ctx.fillStyle = 'white'; ctx.font = '700 82px Inter, Arial'; ctx.textAlign = 'center'; ctx.textBaseline = 'middle';
  'ABCDEFGHIJKLMNOPQRSTUVWXYZ'.split('').forEach((letter, index) => { const x = (index % 6) * 170 + 85; const y = Math.floor(index / 6) * 205 + 102; ctx.fillText(letter, x, y); });
  const texture = new THREE.CanvasTexture(canvas); texture.colorSpace = THREE.SRGBColorSpace; texture.minFilter = THREE.LinearFilter; texture.magFilter = THREE.LinearFilter; return texture;
}

function useAudio() {
  const ctx = useRef<AudioContext | null>(null); const analyser = useRef<AnalyserNode | null>(null); const gain = useRef<GainNode | null>(null); const nodes = useRef<OscillatorNode[]>([]); const media = useRef<HTMLAudioElement | null>(null); const source = useRef<MediaElementAudioSourceNode | null>(null); const microphone = useRef<MediaStreamAudioSourceNode | null>(null); const stream = useRef<MediaStream | null>(null); const [playing, setPlaying] = useState(false); const [micLive, setMicLive] = useState(false);
  const boot = useCallback(async () => { if (!ctx.current) { ctx.current = new AudioContext(); analyser.current = ctx.current.createAnalyser(); analyser.current.fftSize = 512; analyser.current.smoothingTimeConstant = .76; gain.current = ctx.current.createGain(); gain.current.gain.value = .14; gain.current.connect(analyser.current); analyser.current.connect(ctx.current.destination); } await ctx.current.resume(); return ctx.current; }, []);
  const synth = useCallback(async () => { const c = await boot(); if (nodes.current.length) return; const bass = c.createOscillator(), tone = c.createOscillator(), g = c.createGain(); bass.type='sine'; bass.frequency.value=48; tone.type='triangle'; tone.frequency.value=164; g.gain.value=.035; bass.connect(g).connect(gain.current!); tone.connect(gain.current!); bass.start(); tone.start(); nodes.current=[bass,tone]; },[boot]);
  const stopMicrophone = useCallback(() => { microphone.current?.disconnect(); microphone.current = null; stream.current?.getTracks().forEach(track => track.stop()); stream.current = null; setMicLive(false); }, []);
  const toggleMicrophone = useCallback(async () => { if (micLive) { stopMicrophone(); return; } nodes.current.forEach(node => node.stop()); nodes.current=[]; media.current?.pause(); setPlaying(false); try { const c=await boot(); const nextStream=await navigator.mediaDevices.getUserMedia({audio:{echoCancellation:false,noiseSuppression:false,autoGainControl:false}}); const nextSource=c.createMediaStreamSource(nextStream); nextSource.connect(analyser.current!); stream.current=nextStream; microphone.current=nextSource; setMicLive(true); } catch { setMicLive(false); } }, [boot,micLive,stopMicrophone]);
  const toggle = useCallback(async()=>{ if(micLive)stopMicrophone(); if(media.current?.src){if(media.current.paused) await media.current.play();else media.current.pause();return;} if(playing){nodes.current.forEach(n=>n.stop());nodes.current=[];setPlaying(false);}else{await synth();setPlaying(true);}},[micLive,playing,stopMicrophone,synth]);
  const load = useCallback(async(file:File)=>{nodes.current.forEach(n=>n.stop());nodes.current=[];const c=await boot();if(!media.current)media.current=new Audio();if(!source.current){source.current=c.createMediaElementSource(media.current);source.current.connect(gain.current!);}media.current.src=URL.createObjectURL(file);media.current.onplay=()=>setPlaying(true);media.current.onpause=()=>setPlaying(false);await media.current.play();},[boot]);
  useEffect(()=>()=>{nodes.current.forEach(n=>n.stop());media.current?.pause();microphone.current?.disconnect();stream.current?.getTracks().forEach(track=>track.stop());ctx.current?.close();},[]); return {analyser,playing,micLive,toggle,toggleMicrophone,load};
}

function LetterField({ analyser }: { analyser: React.RefObject<AnalyserNode | null> }) {
  const mount = useRef<HTMLDivElement>(null);
  useEffect(() => {
    const host=mount.current!; const scene=new THREE.Scene(); scene.fog=new THREE.FogExp2(0x02020a,.038); const camera=new THREE.PerspectiveCamera(57,1,.1,100); camera.position.set(0,0,18);
    const renderer=new THREE.WebGLRenderer({antialias:false,alpha:false,powerPreference:'high-performance'}); renderer.setPixelRatio(Math.min(devicePixelRatio,2)); host.appendChild(renderer.domElement);
    const position=new Float32Array(COUNT*3), velocity=new Float32Array(COUNT*3), random=new Float32Array(COUNT), char=new Float32Array(COUNT), seed=new Float32Array(COUNT);
    for(let i=0;i<COUNT;i++){const p=i*3;position[p]=(Math.random()-.5)*26;position[p+1]=(Math.random()-.5)*22;position[p+2]=(Math.random()-.5)*25;velocity[p]=(Math.random()-.5)*.5;velocity[p+1]=.5+Math.random()*1.4;velocity[p+2]=(Math.random()-.5)*.4;random[i]=Math.random();char[i]=Math.floor(Math.random()*26);seed[i]=Math.random()*100;}
    const geo=new THREE.BufferGeometry();geo.setAttribute('position',new THREE.BufferAttribute(position,3));geo.setAttribute('aVelocity',new THREE.BufferAttribute(velocity,3));geo.setAttribute('aRandom',new THREE.BufferAttribute(random,1));geo.setAttribute('aChar',new THREE.BufferAttribute(char,1));geo.setAttribute('aSeed',new THREE.BufferAttribute(seed,1));
    const material=new THREE.ShaderMaterial({transparent:true,depthWrite:false,blending:THREE.AdditiveBlending,uniforms:{uTime:{value:0},uBass:{value:0},uHigh:{value:0},uBeat:{value:0},uAtlas:{value:makeAlphabetAtlas()}},vertexShader:`attribute vec3 aVelocity;attribute float aRandom;attribute float aChar;attribute float aSeed;uniform float uTime,uBass,uHigh,uBeat;varying float vChar,vGlow,vAlpha;void main(){vec3 p=position;float fall=mod(p.y-uTime*(.55+aVelocity.y*.45),24.)-12.;p.y=fall;p.x+=sin(uTime*.7+aSeed)*uHigh*.35; p.z+=cos(uTime*.9+aSeed)*uHigh*.5;float d=length(p.xy);vec2 dir=normalize(p.xy+vec2(.001));float shock=exp(-abs(d-uBeat*9.)*2.2)*uBeat*(1.3+aRandom*2.);p.xy+=dir*shock; p.z+=shock*(aRandom-.3);vec4 mv=modelViewMatrix*vec4(p,1.);gl_Position=projectionMatrix*mv;gl_PointSize=(13.+aRandom*23.+uBass*18.)*(1.+uBeat*.8)*(26./-mv.z);vChar=aChar;vGlow=uBeat+uBass;vAlpha=smoothstep(-18.,-4.,mv.z)*(1.-smoothstep(-4.,6.,mv.z));}`,fragmentShader:`uniform sampler2D uAtlas;varying float vChar,vGlow,vAlpha;void main(){float col=mod(vChar,6.);float row=floor(vChar/6.);vec2 uv=(vec2(col,row)+gl_PointCoord)/vec2(6.,5.);float letter=texture2D(uAtlas,uv).r;float glow=smoothstep(.0,.55,letter);vec3 cyan=vec3(.21,.75,1.);vec3 violet=vec3(.72,.25,1.);vec3 color=mix(cyan,violet,fract(vChar*.37));color+=vGlow*vec3(.5,.25,.9);float halo=smoothstep(.8,.0,length(gl_PointCoord-.5))* .15;gl_FragColor=vec4(color,letter*vAlpha*.82+halo*vAlpha);}`});
    const points=new THREE.Points(geo,material);scene.add(points); const frequencies=new Uint8Array(256);let beat=0,lastBass=0,raf=0;const clock=new THREE.Clock();
    const resize=()=>{const w=host.clientWidth,h=host.clientHeight;camera.aspect=w/h;camera.updateProjectionMatrix();renderer.setSize(w,h);};resize();const observer=new ResizeObserver(resize);observer.observe(host);
    const tick=()=>{const t=clock.getElapsedTime();const a=analyser.current;if(a){a.getByteFrequencyData(frequencies);const bass=frequencies.slice(1,20).reduce((s,v)=>s+v,0)/(19*255);const high=frequencies.slice(55,150).reduce((s,v)=>s+v,0)/(95*255);if(bass>.48&&bass>lastBass*1.18)beat=1;lastBass=lastBass*.82+bass*.18;material.uniforms.uBass.value=bass;material.uniforms.uHigh.value=high;}else{material.uniforms.uBass.value=.15+Math.sin(t*2.2)*.08;material.uniforms.uHigh.value=.12+Math.sin(t*3.7)*.06;if(Math.sin(t*1.8)>.992)beat=1;}beat*=.94;material.uniforms.uTime.value=t;material.uniforms.uBeat.value=beat;camera.position.x=Math.sin(t*.12)*1.5;camera.position.y=Math.cos(t*.17)*.8;camera.lookAt(0,0,0);renderer.render(scene,camera);raf=requestAnimationFrame(tick);};tick();return()=>{cancelAnimationFrame(raf);observer.disconnect();geo.dispose();material.dispose();material.uniforms.uAtlas.value.dispose();renderer.dispose();host.removeChild(renderer.domElement);};
  },[analyser]);return <div className="letter-canvas" ref={mount}/>;
}

function App(){const input=useRef<HTMLInputElement>(null);const {analyser,playing,micLive,toggle,toggleMicrophone,load}=useAudio();return <main className="letter-universe"><LetterField analyser={analyser}/><header><span className="mark"/>LETTER UNIVERSE</header><div className="copy"><h1>每一次节拍，<br/>重写坠落的字母。</h1><p>低频制造冲击，高频释放震颤。</p></div><div className="audio-controls"><button onClick={()=>void toggle()} className="play" aria-label={playing?'暂停合成音乐':'播放合成音乐'}>{playing?<Pause fill="currentColor"/>:<Play fill="currentColor"/>}</button><button onClick={()=>void toggleMicrophone()} className={`microphone ${micLive?'active':''}`} aria-label={micLive?'关闭麦克风':'开启麦克风'}>{micLive?<MicOff/>:<Mic/>}<span>{micLive?'麦克风监听中':'麦克风'}</span></button><button onClick={()=>input.current?.click()} className="upload"><Upload/>导入音乐</button><input hidden ref={input} type="file" accept="audio/*" onChange={e=>{const f=e.target.files?.[0];if(f)void load(f);}}/></div><div className="instruction">麦克风可监听扬声器音乐 · 每拍一次，字母宇宙重构</div></main>}
createRoot(document.getElementById('root')!).render(<StrictMode><App/></StrictMode>);
