import { StrictMode, useCallback, useEffect, useRef, useState } from 'react';
import * as THREE from 'three';
import { OrbitControls } from 'three/addons/controls/OrbitControls.js';
import { createRoot } from 'react-dom/client';
import { Mic, MicOff, Pause, Play, Upload } from 'lucide-react';
import './letter-universe.css';

const COUNT = 5200;

function makeAlphabetAtlas() {
  const canvas = document.createElement('canvas'); canvas.width = 1024; canvas.height = 1024;
  const ctx = canvas.getContext('2d')!; ctx.clearRect(0, 0, 1024, 1024); ctx.fillStyle = 'white'; ctx.font = '700 82px Inter, Arial'; ctx.textAlign = 'center'; ctx.textBaseline = 'middle';
  'ABCDEFGHIJKLMNOPQRSTUVWXYZ'.split('').forEach((letter, index) => { const x = (index % 6) * 170 + 85; const y = Math.floor(index / 6) * 205 + 102; ctx.fillText(letter, x, y); });
  const texture = new THREE.CanvasTexture(canvas); texture.colorSpace = THREE.SRGBColorSpace; texture.minFilter = THREE.LinearFilter; texture.magFilter = THREE.LinearFilter; return texture;
}

function useAudio() {
  const ctx = useRef<AudioContext | null>(null); const analyser = useRef<AnalyserNode | null>(null); const gain = useRef<GainNode | null>(null); const nodes = useRef<OscillatorNode[]>([]); const media = useRef<HTMLAudioElement | null>(null); const source = useRef<MediaElementAudioSourceNode | null>(null); const microphone = useRef<MediaStreamAudioSourceNode | null>(null); const stream = useRef<MediaStream | null>(null); const [playing, setPlaying] = useState(false); const [micLive, setMicLive] = useState(false);
  const boot = useCallback(async () => { if (!ctx.current) { ctx.current = new AudioContext(); analyser.current = ctx.current.createAnalyser(); analyser.current.fftSize = 512; analyser.current.smoothingTimeConstant = .76; gain.current = ctx.current.createGain(); gain.current.gain.value = .14; gain.current.connect(analyser.current); analyser.current.connect(ctx.current.destination); } await ctx.current.resume(); return ctx.current; }, []);
  const synth = useCallback(async () => { const c = await boot(); if (nodes.current.length) return; const bass = c.createOscillator(), tone = c.createOscillator(), g = c.createGain(); bass.type='sine'; bass.frequency.value=48; tone.type='triangle'; tone.frequency.value=164; g.gain.value=.035; bass.connect(g).connect(gain.current!); tone.connect(gain.current!); bass.start(); tone.start(); nodes.current=[bass,tone]; },[boot]);
  const stopMicrophone = useCallback(() => { microphone.current?.disconnect(); microphone.current = null; stream.current?.getTracks().forEach(track => track.stop()); stream.current = null; setMicLive(false); }, []);
  const toggleMicrophone = useCallback(async () => { if (micLive) { stopMicrophone(); return; } nodes.current.forEach(node => node.stop()); nodes.current=[]; media.current?.pause(); setPlaying(false); try { const c=await boot(); const nextStream=await navigator.mediaDevices.getUserMedia({audio:{echoCancellation:false,noiseSuppression:false,autoGainControl:false}}); const nextSource=c.createMediaStreamSource(nextStream); nextSource.connect(analyser.current!); stream.current=nextStream; microphone.current=nextSource; setMicLive(true); } catch { setMicLive(false); } }, [boot,micLive,stopMicrophone]);
  const toggle = useCallback(async()=>{ if(micLive)stopMicrophone(); if(media.current?.src){if(media.current.paused) await media.current.play();else media.current.pause();return;} if(playing){nodes.current.forEach(n=>n.stop());nodes.current=[];setPlaying(false);}else{await synth();setPlaying(true);}},[micLive,playing,stopMicrophone,synth]);
  const load = useCallback(async(file:File)=>{nodes.current.forEach(n=>n.stop());nodes.current=[];const c=await boot();if(!media.current)media.current=new Audio();if(!source.current){source.current=c.createMediaElementSource(media.current);source.current.connect(gain.current!);}media.current.src=URL.createObjectURL(file);media.current.onplay=()=>setPlaying(true);media.current.onpause=()=>setPlaying(false);await media.current.play();},[boot]);
  useEffect(()=>()=>{nodes.current.forEach(n=>n.stop());media.current?.pause();microphone.current?.disconnect();stream.current?.getTracks().forEach(track=>track.stop());ctx.current?.close();},[]); return {analyser,playing,micLive,toggle,toggleMicrophone,load};
}

function LetterField({ analyser }: { analyser: React.RefObject<AnalyserNode | null> }) {
  const mount = useRef<HTMLDivElement>(null);
  useEffect(() => {
    const host=mount.current!; const scene=new THREE.Scene(); scene.fog=new THREE.FogExp2(0x02020a,.032); const camera=new THREE.PerspectiveCamera(57,1,.1,100); camera.position.set(0,0,22);
    const renderer=new THREE.WebGLRenderer({antialias:false,alpha:false,powerPreference:'high-performance'}); renderer.setPixelRatio(Math.min(devicePixelRatio,2)); host.appendChild(renderer.domElement);
    const controls=new OrbitControls(camera,renderer.domElement); controls.target.set(0,0,0); controls.enableDamping=true; controls.dampingFactor=.045; controls.enablePan=true; controls.minDistance=7; controls.maxDistance=42; controls.maxPolarAngle=Math.PI*.88; controls.minPolarAngle=Math.PI*.12; renderer.domElement.style.cursor='grab'; controls.addEventListener('start',()=>{renderer.domElement.style.cursor='grabbing';}); controls.addEventListener('end',()=>{renderer.domElement.style.cursor='grab';});
    const position=new Float32Array(COUNT*3), velocity=new Float32Array(COUNT*3), random=new Float32Array(COUNT), char=new Float32Array(COUNT), seed=new Float32Array(COUNT);
    for(let i=0;i<COUNT;i++){const p=i*3;const depth=Math.pow(Math.random(),1.72);position[p]=(Math.random()-.5)*(13+depth*21);position[p+1]=(Math.random()-.5)*(11+depth*17);position[p+2]=8-depth*42;velocity[p]=(Math.random()-.5)*.5;velocity[p+1]=.5+Math.random()*1.4;velocity[p+2]=(Math.random()-.5)*.4;random[i]=Math.random();char[i]=Math.floor(Math.random()*26);seed[i]=Math.random()*100;}
    const geo=new THREE.BufferGeometry();geo.setAttribute('position',new THREE.BufferAttribute(position,3));geo.setAttribute('aVelocity',new THREE.BufferAttribute(velocity,3));geo.setAttribute('aRandom',new THREE.BufferAttribute(random,1));geo.setAttribute('aChar',new THREE.BufferAttribute(char,1));geo.setAttribute('aSeed',new THREE.BufferAttribute(seed,1));
    const material=new THREE.ShaderMaterial({transparent:true,depthWrite:true,blending:THREE.NormalBlending,uniforms:{uTime:{value:0},uBass:{value:0},uMid:{value:0},uHigh:{value:0},uBeat:{value:0},uAfterglow:{value:0},uAtlas:{value:makeAlphabetAtlas()}},vertexShader:`attribute vec3 aVelocity;attribute float aRandom;attribute float aChar;attribute float aSeed;uniform float uTime,uBass,uMid,uHigh,uBeat,uAfterglow;varying float vChar,vGlow,vAlpha;void main(){vec3 p=position;float fall=mod(p.y-uTime*(.48+aVelocity.y*(.25+uMid*.35)),24.)-12.;p.y=fall;p.x+=sin(uTime*(.24+uMid*.18)+aSeed)*(.035+uHigh*.10);p.z+=cos(uTime*(.28+uMid*.12)+aSeed)*(.04+uHigh*.12);float d=length(p.xy);vec2 dir=normalize(p.xy+vec2(.001));float shock=exp(-abs(d-uBeat*7.)*2.8)*uBeat*(.22+aRandom*.32);p.xy+=dir*shock;p.z+=shock*(aRandom-.3);vec4 mv=modelViewMatrix*vec4(p,1.);gl_Position=projectionMatrix*mv;gl_PointSize=(8.+aRandom*15.+uBass*7.)*(1.+uAfterglow*.16)*(24./-mv.z);vChar=aChar;vGlow=uAfterglow*.22+uBass*.45+uHigh*.08;vAlpha=smoothstep(-22.,-5.,mv.z)*(1.-smoothstep(-4.,7.,mv.z));}`,fragmentShader:`uniform sampler2D uAtlas;varying float vChar,vGlow,vAlpha;void main(){float col=mod(vChar,6.);float row=floor(vChar/6.);vec2 uv=(vec2(col,row)+gl_PointCoord)/vec2(6.,5.);float letter=texture2D(uAtlas,uv).r;if(letter<.16)discard;vec3 cyan=vec3(.21,.75,1.);vec3 violet=vec3(.72,.25,1.);vec3 color=mix(cyan,violet,fract(vChar*.37));color+=vGlow*vec3(.32,.18,.45);gl_FragColor=vec4(color,letter*vAlpha*.68);}`});
    const points=new THREE.Points(geo,material);scene.add(points); const frequencies=new Uint8Array(256); const previous=new Uint8Array(256); let beat=0,afterglow=0,bassMean=.08,bassDeviation=.03,fluxMean=.03,fluxDeviation=.015,noiseFloor=.008,lastKick=-1,lastOnset=-1,raf=0;const clock=new THREE.Clock();
    const resize=()=>{const w=host.clientWidth,h=host.clientHeight;camera.aspect=w/h;camera.updateProjectionMatrix();renderer.setSize(w,h);};resize();const observer=new ResizeObserver(resize);observer.observe(host);
    const avg=(from:number,to:number)=>{let sum=0;for(let i=from;i<to;i++)sum+=frequencies[i];return sum/((to-from)*255);}; const tick=()=>{const t=clock.getElapsedTime();const a=analyser.current;if(a){a.getByteFrequencyData(frequencies);let bass=avg(1,18),mid=avg(18,72),high=avg(72,168);const rawEnergy=bass*.55+mid*.3+high*.15;if(rawEnergy<noiseFloor+.055)noiseFloor=noiseFloor*.985+rawEnergy*.015;const gate=THREE.MathUtils.clamp((rawEnergy-noiseFloor-.025)/.11,0,1);bass*=gate;mid*=gate;high*=gate;let flux=0;for(let i=2;i<180;i++){flux+=Math.max(0,frequencies[i]-previous[i]);previous[i]=frequencies[i];}flux=flux/(178*255)*gate;const bassThreshold=bassMean+Math.max(.035,bassDeviation*1.75),fluxThreshold=fluxMean+Math.max(.018,fluxDeviation*1.9);const kick=gate>.12&&bass>bassThreshold&&bass>.12&&t-lastKick>.42;const onset=gate>.16&&flux>fluxThreshold&&t-lastOnset>.3;if(kick){beat=.58;afterglow=1;lastKick=t;}else if(onset){beat=Math.max(beat,.24);afterglow=Math.max(afterglow,.58);lastOnset=t;}bassMean=bassMean*.94+bass*.06;bassDeviation=bassDeviation*.94+Math.abs(bass-bassMean)*.06;fluxMean=fluxMean*.9+flux*.1;fluxDeviation=fluxDeviation*.9+Math.abs(flux-fluxMean)*.1;material.uniforms.uBass.value=bass;material.uniforms.uMid.value=mid;material.uniforms.uHigh.value=high;}else{material.uniforms.uBass.value=.15+Math.sin(t*2.2)*.08;material.uniforms.uMid.value=.18+Math.sin(t*1.4)*.07;material.uniforms.uHigh.value=.12+Math.sin(t*3.7)*.06;if(Math.sin(t*1.8)>.992){beat=.58;afterglow=1;}}beat*=.84;afterglow*=.975;material.uniforms.uTime.value=t;material.uniforms.uBeat.value=beat;material.uniforms.uAfterglow.value=afterglow;controls.update();renderer.render(scene,camera);raf=requestAnimationFrame(tick);};tick();return()=>{cancelAnimationFrame(raf);observer.disconnect();controls.dispose();geo.dispose();material.dispose();material.uniforms.uAtlas.value.dispose();renderer.dispose();host.removeChild(renderer.domElement);};
  },[analyser]);return <div className="letter-canvas" ref={mount}/>;
}

function App(){const input=useRef<HTMLInputElement>(null);const {analyser,playing,micLive,toggle,toggleMicrophone,load}=useAudio();return <main className="letter-universe"><LetterField analyser={analyser}/><header><span className="mark"/>LETTER UNIVERSE</header><div className="copy"><h1>每一次节拍，<br/>重写坠落的字母。</h1><p>低频制造冲击，高频释放震颤。</p></div><div className="audio-controls"><button onClick={()=>void toggle()} className="play" aria-label={playing?'暂停合成音乐':'播放合成音乐'}>{playing?<Pause fill="currentColor"/>:<Play fill="currentColor"/>}</button><button onClick={()=>void toggleMicrophone()} className={`microphone ${micLive?'active':''}`} aria-label={micLive?'关闭麦克风':'开启麦克风'}>{micLive?<MicOff/>:<Mic/>}<span>{micLive?'麦克风监听中':'麦克风'}</span></button><button onClick={()=>input.current?.click()} className="upload"><Upload/>导入音乐</button><input hidden ref={input} type="file" accept="audio/*" onChange={e=>{const f=e.target.files?.[0];if(f)void load(f);}}/></div><div className="instruction">麦克风可监听扬声器音乐 · 每拍一次，字母宇宙重构</div></main>}
createRoot(document.getElementById('root')!).render(<StrictMode><App/></StrictMode>);
